### ISSUE TITLE
(UndefinedFunctionError) function :telemetry.span/3 is undefined or private

### ISSUE THREAD

**Issue by btkostner** [spandex-project/spandex_datadog#36]
I am not using the spandex phoenix or plug wrapper. This is for a Broadway project so we are just using the `@decorate trace()` around `handle_message/3`. This is the start of the trace. It looks like so (simplified for the issue report):

```ex
defmodule Bullhorn.Broadway do
  use Broadway
  use Spandex.Decorators

  alias Broadway.Message

  @impl true
  @decorate trace(service: :bullhorn, type: :function)
  def handle_message(_, %Message{data: data} = message, _context) do
    # do some logic here

    with {:error, reason} <- notify_handler(bottle.resource) do
      Tracer.span_error(%RuntimeError{message: inspect(reason)}, nil)
      Logger.error(reason)
    end

    message
  end
end
```

This project is public, so if you want to take a look at the code more, it's here: https://github.com/system76/bullhorn/blob/datadog/lib/bullhorn/broadway.ex

This runs fine on `1.0.0` and gives what we would expect in Datadog. Telemetry is up to date `0.4.1` so that shouldn't be a problem, but with `1.1.0` we get a telemetry function error:

```ex
** (UndefinedFunctionError) function :telemetry.span/3 is undefined or private
    (telemetry 0.4.1) :telemetry.span([:spandex_datadog, :send_trace], %{trace: %Spandex.Trace{baggage: [], id: 1327066196628998004, priority: 1, spans: [%Spandex.Span{completion_time: 1613544877848155790, env: "staging", error: [exception: %RuntimeError{message: "testing"}, stacktrace: [{Bullhorn.Mailer, :send, 1, [file: 'lib/bullhorn/mailer.ex', line: 12]}, {Bullhorn.Broadway, :handle_message, 3, [file: 'lib/bullhorn/broadway.ex', line: 42]}, {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 680]}, {:elixir, :recur_eval, 3, [file: 'src/elixir.erl', line: 280]}, {:elixir, :eval_forms, 3, [file: 'src/elixir.erl', line: 265]}, {IEx.Evaluator, :handle_eval, 5, [file: 'lib/iex/evaluator.ex', line: 261]}, {IEx.Evaluator, :do_eval, 3, [file: 'lib/iex/evaluator.ex', line: 242]}, {IEx.Evaluator, :eval, 3, [file: 'lib/iex/evaluator.ex', line: 220]}]], http: nil, id: 5207733743678132948, name: "Bullhorn.Mailer.send/1", parent_id: 7455211922707614479, private: [], resource: "Bullhorn.Mailer.send/1", service: :mailgun, services: [], sql_query: nil, start: 1613544877846395793, tags: [], trace_id: 1327066196628998004, type: :web}, %Spandex.Span{completion_time: 1613544877848197886, env: "staging", error: [exception: %RuntimeError{message: "testing"}, stacktrace: [{Bullhorn.Mailer, :send, 1, [file: 'lib/bullhorn/mailer.ex', line: 12]}, {Bullhorn.Broadway, :handle_message, 3, [file: 'lib/bullhorn/broadway.ex', line: 42]}, {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 680]}, {:elixir, :recur_eval, 3, [file: 'src/elixir.erl', line: 280]}, {:elixir, :eval_forms, 3, [file: 'src/elixir.erl', line: 265]}, {IEx.Evaluator, :handle_eval, 5, [file: 'lib/iex/evaluator.ex', line: 261]}, {IEx.Evaluator, :do_eval, 3, [file: 'lib/iex/evaluator.ex', line: 242]}, {IEx.Evaluator, :eval, 3, [file: 'lib/iex/evaluator.ex', line: 220]}]], http: nil, id: 7455211922707614479, name: "Bullhorn.Broadway.handle_message/3", parent_id: nil, private: [], resource: nil, service: :bullhorn, services: [], sql_query: nil, start: 1613544877820785676, tags: [], trace_id: 1327066196628998004, type: :function}], stack: []}}, #Function<20.14287641/0 in SpandexDatadog.ApiServer.send_trace/2>)
    (spandex 3.0.3) lib/spandex.ex:178: Spandex.finish_trace/1
    (bullhorn 0.1.0) lib/bullhorn/broadway.ex:1: Bullhorn.Broadway.handle_message/3
```

**Comment by btkostner** [comment]
Never mind. This is me not reading the telemetry changelog :facepalm:
